/*
389. Find the Difference
Easy
Topics
Companies
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"

Constraints:

0 <= s.length <= 1000
t.length == s.length + 1
s and t consist of lowercase English letters.
*/
package main

import (
	"fmt"
)

//func findTheDifference(s string, t string) byte {
//	if len(s) == 0 {
//		return t[0]
//	}
//	var res byte
//	sr := []rune(s)
//	sort.Slice(sr, func(i int, j int) bool { return sr[i] < sr[j] })
//	tr := []rune(t)
//	sort.Slice(tr, func(i int, j int) bool { return tr[i] < tr[j] })
//
//	for i := 0; i < len(sr); i++ {
//		if sr[i] != tr[i] {
//			res = byte(tr[i])
//			break
//		}
//
//		if i == len(s)-1 {
//			res = byte(tr[len(sr)])
//			break
//		}
//	}
//	return res
//
//}

func findTheDifference(s string, t string) byte {
	sumS, sumT := 0, 0
	for _, i := range s {
		sumS += int(i)
	}

	for _, i := range t {
		sumT += int(i)
	}

	diff := sumT - sumS

	return byte(diff)
}

func main() {
	fmt.Println(findTheDifference("abcd", "abcde"))
	fmt.Println(findTheDifference("", "y"))
}
